# Generated by Django 4.2.23 on 2025-07-16 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, help_text='Другие пользователи, с которыми установлено соединение.', to=settings.AUTH_USER_MODEL),
        ),
    ]
