# Generated by Django 4.2.23 on 2025-07-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, записавшиеся на тур (на любой дате)', related_name='joined_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Тип/категория тура', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.tourcategory'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tours.toursession'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='tours.toursession'),
        ),
    ]
