# Generated by Django 4.2.23 on 2025-07-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название направления', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание направления')),
                ('region', models.CharField(choices=[('uzbekistan', 'Узбекистан'), ('central_asia', 'Центральная Азия'), ('asia', 'Азия'), ('europe', 'Европа'), ('other', 'Другое')], default='uzbekistan', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Изображение направления', null=True, upload_to='destination_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Направление тура', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.destination'),
        ),
    ]
