# Generated by Django 4.2.23 on 2025-07-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_destination_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
    ]
