# Generated by Django 4.2.23 on 2025-07-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tour_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='main_image',
        ),
    ]
