# Generated by Django 4.2.23 on 2025-07-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
        ('tours', '0005_remove_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Основное изображение тура', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_as_main_image', to='media.media'),
        ),
    ]
