# Generated by Django 4.2.23 on 2025-07-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0006_add_main_image_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('priority', models.IntegerField(choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Низкий')], default=2, verbose_name='Приоритет')),
                ('notes', models.TextField(blank=True, help_text='Заметки пользователя о туре', verbose_name='Личные заметки')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='tours.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_tours', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запланированный тур',
                'verbose_name_plural': 'Запланированные туры',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
