# Generated by Django 4.2.23 on 2025-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTripOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_text', models.TextField(help_text='Описание предложения агентства')),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Trip Offer',
                'verbose_name_plural': 'Custom Trip Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(help_text='Тип поездки (семейный отдых, корпоратив и т.д.)', max_length=100)),
                ('directions', models.TextField(help_text='Куда хочет поехать')),
                ('people_count', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('transport_options', models.TextField(blank=True, help_text='Предпочтительный транспорт')),
                ('wishes', models.TextField(blank=True, help_text='Особые пожелания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('assigned', 'В работе'), ('declined', 'Отклонён'), ('completed', 'Завершён')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_requests', to='agencies.travelagency')),
            ],
            options={
                'verbose_name': 'Custom Trip Request',
                'verbose_name_plural': 'Custom Trip Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
