# Generated by Django 4.2.23 on 2025-07-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtriprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_trip_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtripoffer',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='agencies.travelagency'),
        ),
        migrations.AddField(
            model_name='customtripoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='custom_trips.customtriprequest'),
        ),
    ]
