# Generated by Django 4.2.23 on 2025-07-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма бонуса', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('available_at', models.DateTimeField(help_text='Когда бонус станет доступным для вывода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referral Bonus',
                'verbose_name_plural': 'Referral Bonuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный реферальный код', max_length=20, unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Процент комиссии с продаж', max_digits=5)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма начисленных бонусов', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма уже выплаченных бонусов', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Partner',
                'verbose_name_plural': 'Referral Partners',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(help_text='Номер карты для перевода', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, help_text='Комментарий администратора при отклонении', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='referrals.referralpartner')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
