# Generated by Django 4.2.23 on 2025-07-15 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0001_initial'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpartner',
            name='user',
            field=models.OneToOneField(help_text='Связанный аккаунт пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Бронирование, по которому начислен бонус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='referralbonus',
            name='partner',
            field=models.ForeignKey(help_text='Кому начислен бонус', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='referrals.referralpartner'),
        ),
    ]
