# Generated by Django 4.2.23 on 2025-07-16 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название агентства', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание, информация об агентстве')),
                ('is_active', models.BooleanField(default=True, help_text='Может ли публиковать туры')),
                ('contact_person', models.CharField(blank=True, help_text='Имя контактного лица', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Средняя оценка агентства от пользователей (0.00 - 5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Общее количество отзывов')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Процент комиссии, которую удерживает платформа', max_digits=5)),
                ('payme_merchant_id', models.CharField(blank=True, help_text='Payme Merchant ID для split-интеграции (на будущее)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Agency',
                'verbose_name_plural': 'Travel Agencies',
                'ordering': ['-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Текст отзыва')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agencies.travelagency')),
            ],
            options={
                'verbose_name': 'Agency Review',
                'verbose_name_plural': 'Agency Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
