# Generated by Django 4.2.23 on 2025-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_reserved', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Базовая цена до всех скидок', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Общая скидка (акция+промокод)', max_digits=10)),
                ('bonus_used_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма использованных бонусов', max_digits=10)),
                ('final_price_paid', models.DecimalField(decimal_places=2, default=0, help_text='Финальная сумма, оплаченная картой', max_digits=10)),
                ('selected_transport', models.CharField(blank=True, max_length=100)),
                ('selected_accommodation', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Заявка отправлена'), ('approved', 'Подтверждена менеджером'), ('paid', 'Оплачено'), ('cancelled', 'Отменена'), ('expired', 'Просрочена')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
