# Generated by Django 4.2.23 on 2025-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Уникальный ключ', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Значение')),
                ('description', models.TextField(blank=True, help_text='Описание назначения')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=20)),
                ('source', models.CharField(help_text='Источник события', max_length=100)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, help_text='Дополнительные данные', null=True)),
            ],
            options={
                'verbose_name': 'System Log Entry',
                'verbose_name_plural': 'System Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
